function(sm_append_simple_target_property target property str)
  get_target_property(current_property ${target} ${property})
  if(current_property)
    list(APPEND current_property ${str})
    set_target_properties(${target}
                          PROPERTIES ${property} "${current_property}")
  else()
    set_target_properties(${target} PROPERTIES ${property} ${str})
  endif()
endfunction()

function(sm_add_link_flag target flag)
  if(MSVC)
    # Use a modified form of sm_append_simple_target_property.
    get_target_property(current_property ${target} LINK_FLAGS)
    if(current_property)
      set_target_properties(${target}
                            PROPERTIES LINK_FLAGS "${current_property} ${flag}")
    else()
      set_target_properties(${target} PROPERTIES LINK_FLAGS ${flag})
    endif()
  else()
    sm_append_simple_target_property(${target} LINK_FLAGS ${flag})
  endif()
endfunction()

function(disable_project_warnings projectName)
  if(NOT WITH_EXTERNAL_WARNINGS)
    if(MSVC)
      target_compile_options(${projectName} PRIVATE "/W0")
    elseif(CMAKE_GENERATOR STREQUAL Xcode)
      set_property(TARGET ${projectName} PROPERTY XCODE_ATTRIBUTE_GCC_WARN_INHIBIT_ALL_WARNINGS "YES")
    else()
      target_compile_options(${projectName} PRIVATE "-w")
    endif()
  endif()
endfunction()

function(sm_glob_files out_var)
  set(options RECURSE)
  set(oneValueArgs BASE_DIR)
  set(multiValueArgs PATTERNS EXCLUDE_PATTERNS)
  cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(NOT ARG_BASE_DIR)
    message(FATAL_ERROR "sm_glob_files requires BASE_DIR")
  endif()

  if(NOT ARG_PATTERNS)
    message(FATAL_ERROR "sm_glob_files requires at least one PATTERN")
  endif()

  set(globbed_files)
  foreach(pattern IN LISTS ARG_PATTERNS)
    if(ARG_RECURSE)
      file(GLOB_RECURSE matched_files CONFIGURE_DEPENDS "${ARG_BASE_DIR}/${pattern}")
    else()
      file(GLOB matched_files CONFIGURE_DEPENDS "${ARG_BASE_DIR}/${pattern}")
    endif()
    list(APPEND globbed_files ${matched_files})
  endforeach()

  foreach(pattern IN LISTS ARG_EXCLUDE_PATTERNS)
    if(ARG_RECURSE)
      file(GLOB_RECURSE excluded_files CONFIGURE_DEPENDS "${ARG_BASE_DIR}/${pattern}")
    else()
      file(GLOB excluded_files CONFIGURE_DEPENDS "${ARG_BASE_DIR}/${pattern}")
    endif()
    if(excluded_files)
      list(REMOVE_ITEM globbed_files ${excluded_files})
    endif()
  endforeach()

  list(REMOVE_DUPLICATES globbed_files)
  list(SORT globbed_files)
  set(${out_var} ${globbed_files} PARENT_SCOPE)
endfunction()

macro(check_compile_features
      BIN_DIR
      SOURCE_FILE
      GREETER
      GREET_SUCCESS
      GREET_FAILURE
      TARGET_VAR
      ON_SUCCESS)
  if(NOT DEFINED "${TARGET_VAR}")
    message(STATUS "${GREETER}")
    try_compile(${TARGET_VAR} "${BIN_DIR}" SOURCES "${SOURCE_FILE}")
    if(${TARGET_VAR})
      if(${ON_SUCCESS})
        message(STATUS "${GREETER} - ${GREET_SUCCESS}")
        set(${TARGET_VAR} 1 CACHE INTERNAL "${GREETER}")
      else()
        message(STATUS "${GREETER} - ${GREET_FAILURE}")
        set(${TARGET_VAR} "" CACHE INTERNAL "${GREETER}")
      endif()
    else()
      if(${ON_SUCCESS})
        message(STATUS "${GREETER} - ${GREET_FAILURE}")
        set(${TARGET_VAR} 1 CACHE INTERNAL "${GREETER}")
      else()
        message(STATUS "${GREETER} - ${GREET_SUCCESS}")
        set(${TARGET_VAR} "" CACHE INTERNAL "${GREETER}")
      endif()
    endif()
  endif()
endmacro()
