set(CPACK_PACKAGE_NAME "${SM_EXE_NAME}")
set(CPACK_PACKAGE_VENDOR "${SM_EXE_NAME} Developers")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Rhythm Game Simulator")
set(CPACK_PACKAGE_VERSION_MAJOR "${SM_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${SM_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${SM_VERSION_PATCH}")
if(WITH_FULL_RELEASE)
  set(CPACK_PACKAGE_VERSION "${SM_VERSION_TRADITIONAL}")
else()
  set(CPACK_PACKAGE_VERSION "${SM_VERSION_GIT}")
endif()
set(CPACK_PACKAGE_EXECUTABLES "${SM_EXE_NAME}" "ITGmania")
set(CPACK_RESOURCE_FILE_README "${SM_ROOT_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${SM_CMAKE_DIR}/license_install.txt")

if(WIN32)
  # WiX Toolset can be provided by the Visual Studio Installer, chocolatey, etc
  # https://cmake.org/cmake/help/latest/cpack_gen/wix.html
  # This config uses the default WiX UI settings with only needed flags set.
  set(CPACK_GENERATOR WIX)
  set(CPACK_SYSTEM_NAME "Windows")
  set(CPACK_WIX_UPGRADE_GUID "a1dcf4ac-e756-4625-8b53-2584e8b7a69a")
  set(CPACK_WIX_SKIP_PROGRAM_FOLDER ON)
  set(INSTALL_ROOT "C:/Games/ITGmania")
  set(CPACK_PACKAGE_INSTALL_DIRECTORY "${INSTALL_ROOT}")
  set(CPACK_WIX_UI_REF "WixUI_InstallDir")
  set(CPACK_WIX_PRODUCT_ICON "${SM_INSTALLER_DIR}/install.ico")
  set(CPACK_WIX_UI_BANNER "${SM_INSTALLER_DIR}/header.bmp")
  set(CPACK_WIX_PROGRAM_MENU_FOLDER "ITGmania")
  set(CPACK_WIX_HELP_LINK "https://github.com/itgmania/itgmania/issues")
  set(CPACK_WIX_PRODUCT_NAME "${SM_EXE_NAME} ${CPACK_PACKAGE_VERSION}")
  set(CPACK_WIX_URL_INFO_ABOUT "https://www.itgmania.com/")
  set(CPACK_WIX_PROPERTY_ARPURLINFOABOUT "https://www.itgmania.com/")
elseif(MACOSX)
  set(CPACK_GENERATOR DragNDrop)
  set(CPACK_DMG_VOLUME_NAME "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}")
  set(CPACK_DMG_FORMAT ULMO)  # lzma-compressed image

  if(CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
    set(CPACK_SYSTEM_NAME "macOS-M1")
  elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
    set(CPACK_SYSTEM_NAME "macOS-Intel")
  else()
    message(FATAL_ERROR
      "Unsupported macOS architecture: ${CMAKE_OSX_ARCHITECTURES}, set CMAKE_OSX_ARCHITECTURES to either arm64 or x86_64"
    )
  endif()
else()
  set(CPACK_GENERATOR TGZ)
  if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(CPACK_SYSTEM_NAME "Linux")
  elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
    set(CPACK_SYSTEM_NAME "Linux-arm64")
  else()
    message("Unknown architecture: ${CMAKE_SYSTEM_PROCESSOR}")
    set(CPACK_SYSTEM_NAME "Linux-unknown")
  endif()
endif()

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}")
if(NOT WITH_CLUB_FANTASTIC)
  set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_FILE_NAME}-no-songs")
endif()

include(CPack)
