set(SM_FFMPEG_SRC_DIR "${SM_EXTERN_DIR}/ffmpeg")
set(SM_FFMPEG_INSTALL_DIR "${CMAKE_BINARY_DIR}/ffmpeg-install")
set(SM_FFMPEG_LIB "${SM_FFMPEG_INSTALL_DIR}/lib")
set(SM_FFMPEG_INCLUDE "${SM_FFMPEG_INSTALL_DIR}/include")

# Keep generated FFmpeg headers present for IntelliSense and early compile steps.
# FFmpeg's configure step will replace these with real generated content.
if(NOT EXISTS "${SM_FFMPEG_SRC_DIR}/config.h")
  file(WRITE "${SM_FFMPEG_SRC_DIR}/config.h"
"/* Autogenerated placeholder. Replaced by FFmpeg configure. */\n")
endif()
if(NOT EXISTS "${SM_FFMPEG_SRC_DIR}/libavutil/avconfig.h")
  file(WRITE "${SM_FFMPEG_SRC_DIR}/libavutil/avconfig.h"
"/* Autogenerated placeholder. Replaced by FFmpeg configure. */\n")
endif()

function(sm_to_msys_path INPUT_PATH OUTPUT_VAR)
  file(TO_CMAKE_PATH "${INPUT_PATH}" _path)
  if(_path MATCHES "^([A-Za-z]):/(.*)")
    string(TOLOWER "${CMAKE_MATCH_1}" _drive)
    set(_path "/${_drive}/${CMAKE_MATCH_2}")
  endif()
  set(${OUTPUT_VAR} "${_path}" PARENT_SCOPE)
endfunction()

set(SM_FFMPEG_MAKE_COMMAND)
set(SM_FFMPEG_CONFIGURE_COMMAND)

if(WIN32)
  if(NOT MSVC)
    message(FATAL_ERROR "FFmpeg: Windows build requires the MSVC toolchain.")
  endif()

  find_program(SM_FFMPEG_BASH
               NAMES bash.exe bash
               HINTS
                 "$ENV{FFMPEG_BASH}"
                 "$ENV{MSYS2_PATH}/usr/bin"
                 "C:/Program Files/Git/bin"
                 "C:/Program Files/Git/usr/bin"
                 "C:/msys64/usr/bin"
                 "C:/msys32/usr/bin")

  if(NOT SM_FFMPEG_BASH)
    message(FATAL_ERROR
      "FFmpeg: Could not find bash.exe required for configure on Windows. Install Git for Windows or MSYS2, or set FFMPEG_BASH to the full path of bash.exe."
    )
  endif()

  message(STATUS "FFmpeg: Using bash at ${SM_FFMPEG_BASH}")
  message(STATUS "FFmpeg: Building with make via bash (configure uses --toolchain=msvc)")

  sm_to_msys_path("${SM_FFMPEG_SRC_DIR}" _MSYS2_SRC_DIR)
  sm_to_msys_path("${SM_FFMPEG_INSTALL_DIR}" _MSYS2_INSTALL_DIR)

  if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(_FFMPEG_ARCH "x86_64")
    set(_FFMPEG_TARGET_OS "win64")
  else()
    set(_FFMPEG_ARCH "x86")
    set(_FFMPEG_TARGET_OS "win32")
  endif()

  set(_FFMPEG_WINDOWS_CONFIGURE
      "--prefix=${_MSYS2_INSTALL_DIR}"
      "--toolchain=msvc"
      "--target-os=${_FFMPEG_TARGET_OS}"
      "--arch=${_FFMPEG_ARCH}"
      "--disable-autodetect"
      "--disable-avdevice"
      "--disable-avfilter"
      "--disable-devices"
      "--disable-doc"
      "--disable-filters"
      "--disable-lzma"
      "--disable-network"
      "--disable-postproc"
      "--disable-programs"
      "--disable-swresample"
      "--disable-vaapi"
      "--disable-bzlib"
      "--enable-gpl"
      "--enable-version3"
      "--disable-pthreads"
      "--enable-w32threads"
      "--enable-static"
      "--disable-shared"
      "--disable-zlib"
      "--disable-asm")

  if(CMAKE_C_FLAGS)
    list(APPEND _FFMPEG_WINDOWS_CONFIGURE "--extra-cflags=${CMAKE_C_FLAGS}")
  endif()
  if(CMAKE_CXX_FLAGS)
    list(APPEND _FFMPEG_WINDOWS_CONFIGURE "--extra-cxxflags=${CMAKE_CXX_FLAGS}")
  endif()
  if(NOT WITH_EXTERNAL_WARNINGS)
    list(APPEND _FFMPEG_WINDOWS_CONFIGURE "--extra-cflags=-w")
  endif()

  set(_ffmpeg_configure_script "${CMAKE_BINARY_DIR}/ffmpeg_configure.sh")
  file(WRITE "${_ffmpeg_configure_script}" "#!/usr/bin/env bash\n")
  file(APPEND "${_ffmpeg_configure_script}" "set -euo pipefail\n")
  file(APPEND "${_ffmpeg_configure_script}" "cd \"${_MSYS2_SRC_DIR}\"\n")
  file(APPEND "${_ffmpeg_configure_script}" "./configure")
  foreach(_arg IN LISTS _FFMPEG_WINDOWS_CONFIGURE)
    string(REPLACE "\"" "\\\"" _quoted_arg "${_arg}")
     file(APPEND "${_ffmpeg_configure_script}" " \\\n  \"${_quoted_arg}\"")
  endforeach()
  file(APPEND "${_ffmpeg_configure_script}" "\n")

  set(SM_FFMPEG_CONFIGURE_COMMAND
      "${SM_FFMPEG_BASH}"
      "${_ffmpeg_configure_script}")

    set(_ffmpeg_make_script "${CMAKE_BINARY_DIR}/ffmpeg_make.sh")
    file(WRITE "${_ffmpeg_make_script}" "#!/usr/bin/env bash\n")
    file(APPEND "${_ffmpeg_make_script}" "set -euo pipefail\n")
    file(APPEND "${_ffmpeg_make_script}" "cd \"${_MSYS2_SRC_DIR}\"\n")
    file(APPEND "${_ffmpeg_make_script}" "echo 'FFmpeg: running configure...'\n")
    file(APPEND "${_ffmpeg_make_script}" "\"${SM_FFMPEG_BASH}\" \"${_ffmpeg_configure_script}\"\n")
    file(APPEND "${_ffmpeg_make_script}" "make install\n")

    set(SM_FFMPEG_MAKE_COMMAND
      "${SM_FFMPEG_BASH}"
      "${_ffmpeg_make_script}")
else()
  set(SM_FFMPEG_CONFIGURE_EXE "${SM_FFMPEG_SRC_DIR}/configure")
  set(FFMPEG_CONFIGURE
      "${SM_FFMPEG_CONFIGURE_EXE}"
      "--disable-autodetect"
      "--disable-avdevice"
      "--disable-avfilter"
      "--disable-devices"
      "--disable-doc"
      "--disable-filters"
      "--disable-lzma"
      "--disable-network"
      "--disable-postproc"
      "--disable-programs"
      "--disable-swresample"
      "--disable-vaapi"
      "--disable-bzlib"
      "--enable-gpl"
      "--enable-version3"
      "--enable-pthreads"
      "--enable-static"
      "--disable-shared"
      "--enable-zlib"
      "--prefix=${SM_FFMPEG_INSTALL_DIR}")

  set(FFMPEG_CC "${CMAKE_C_COMPILER}")
  set(FFMPEG_CXX "${CMAKE_CXX_COMPILER}")
  if(CMAKE_C_COMPILER_LAUNCHER)
    string(REPLACE ";" " " FFMPEG_C_LAUNCHER "${CMAKE_C_COMPILER_LAUNCHER}")
    set(FFMPEG_CC "${FFMPEG_C_LAUNCHER} ${FFMPEG_CC}")
  endif()
  if(CMAKE_CXX_COMPILER_LAUNCHER)
    string(REPLACE ";" " " FFMPEG_CXX_LAUNCHER "${CMAKE_CXX_COMPILER_LAUNCHER}")
    set(FFMPEG_CXX "${FFMPEG_CXX_LAUNCHER} ${FFMPEG_CXX}")
  endif()
  list(APPEND FFMPEG_CONFIGURE "--cc=${FFMPEG_CC}" "--cxx=${FFMPEG_CXX}")

  if(CMAKE_C_FLAGS)
    list(APPEND FFMPEG_CONFIGURE "--extra-cflags=${CMAKE_C_FLAGS}")
  endif()
  if(CMAKE_CXX_FLAGS)
    list(APPEND FFMPEG_CONFIGURE "--extra-cxxflags=${CMAKE_CXX_FLAGS}")
  endif()

  if(CMAKE_POSITION_INDEPENDENT_CODE)
    list(APPEND FFMPEG_CONFIGURE "--enable-pic")
  endif()

  if(MACOSX)
    list(APPEND FFMPEG_CONFIGURE "--enable-cross-compile")
    list(APPEND FFMPEG_CONFIGURE "--enable-videotoolbox")
    list(APPEND FFMPEG_CONFIGURE "--extra-cflags=-mmacosx-version-min=11")
    if(CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
      list(APPEND FFMPEG_CONFIGURE "--arch=arm64" "--extra-cflags=-arch arm64" "--extra-ldflags=-arch arm64")
    elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
      list(APPEND FFMPEG_CONFIGURE "--arch=x86_64" "--extra-cflags=-arch x86_64" "--extra-ldflags=-arch x86_64")
    else()
      message(FATAL_ERROR
        "Unsupported macOS architecture: ${CMAKE_OSX_ARCHITECTURES}, set CMAKE_OSX_ARCHITECTURES to either arm64 or x86_64"
      )
    endif()
  endif()

  if(NOT WITH_EXTERNAL_WARNINGS)
    list(APPEND FFMPEG_CONFIGURE "--extra-cflags=-w")
  endif()

  set(SM_FFMPEG_CONFIGURE_COMMAND ${FFMPEG_CONFIGURE})

  if(CMAKE_GENERATOR STREQUAL "Xcode" OR CMAKE_GENERATOR MATCHES "Ninja")
    if(DEFINED ENV{CMAKE_BUILD_PARALLEL_LEVEL})
      set(NUM_CORES $ENV{CMAKE_BUILD_PARALLEL_LEVEL})
    else()
      cmake_host_system_information(RESULT NUM_CORES QUERY NUMBER_OF_LOGICAL_CORES)
    endif()
    set(SM_FFMPEG_MAKE_COMMAND "make" "-j${NUM_CORES}" "install")
  else()
    set(SM_FFMPEG_MAKE_COMMAND "make" "install")
  endif()
endif()

externalproject_add("ffmpeg"
                    SOURCE_DIR "${SM_FFMPEG_SRC_DIR}"
                    BUILD_IN_SOURCE TRUE
                    CONFIGURE_COMMAND ${SM_FFMPEG_CONFIGURE_COMMAND}
                    BUILD_COMMAND ${SM_FFMPEG_MAKE_COMMAND}
                    UPDATE_COMMAND ""
                    INSTALL_COMMAND ""
                    TEST_COMMAND ""
                    STEP_TARGETS configure
                    BUILD_BYPRODUCTS
                      "${SM_FFMPEG_SRC_DIR}/config.h"
                      "${SM_FFMPEG_SRC_DIR}/libavutil/avconfig.h"
                      "${SM_FFMPEG_LIB}/libavformat.a"
                      "${SM_FFMPEG_LIB}/libavcodec.a"
                      "${SM_FFMPEG_LIB}/libswscale.a"
                      "${SM_FFMPEG_LIB}/libavutil.a"
                      "${SM_FFMPEG_LIB}/avformat.lib"
                      "${SM_FFMPEG_LIB}/avcodec.lib"
                      "${SM_FFMPEG_LIB}/swscale.lib"
                      "${SM_FFMPEG_LIB}/avutil.lib")
