set(SM_FFMPEG_RELEASE_FILE "${SM_FFMPEG_SRC_DIR}/RELEASE")

set(SM_FFMPEG_VERSION "unknown")
if(EXISTS "${SM_FFMPEG_RELEASE_FILE}")
  file(READ "${SM_FFMPEG_RELEASE_FILE}" SM_FFMPEG_VERSION)
  string(STRIP "${SM_FFMPEG_VERSION}" SM_FFMPEG_VERSION)
endif()

get_filename_component(SM_FFMPEG_CACHE_PARENT "${SM_BUILD_DIR}" DIRECTORY)
set(SM_FFMPEG_CACHE_ROOT
  "${SM_FFMPEG_BUILD_DIR}"
    CACHE PATH
          "Persistent directory used to cache bundled ffmpeg builds by version.")

set(SM_FFMPEG_CACHE_KEY
    "${SM_FFMPEG_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
if(MACOSX AND CMAKE_OSX_ARCHITECTURES)
  string(APPEND SM_FFMPEG_CACHE_KEY "-${CMAKE_OSX_ARCHITECTURES}")
endif()

if(CMAKE_POSITION_INDEPENDENT_CODE)
  string(APPEND SM_FFMPEG_CACHE_KEY "-pic")
endif()

if(NOT WITH_EXTERNAL_WARNINGS)
  string(APPEND SM_FFMPEG_CACHE_KEY "-nowarn")
endif()

string(REPLACE ";" "_" SM_FFMPEG_CACHE_KEY "${SM_FFMPEG_CACHE_KEY}")

set(SM_FFMPEG_CACHE_DIR "${SM_FFMPEG_CACHE_ROOT}/${SM_FFMPEG_CACHE_KEY}")
set(SM_FFMPEG_CACHE_BUILD_DIR "${SM_FFMPEG_CACHE_DIR}/build")
set(SM_FFMPEG_CACHE_INSTALL_DIR "${SM_FFMPEG_CACHE_DIR}/install")

set(SM_FFMPEG_LIB "${SM_FFMPEG_CACHE_INSTALL_DIR}/lib")
set(SM_FFMPEG_INCLUDE "${SM_FFMPEG_CACHE_INSTALL_DIR}/include")

set(SM_FFMPEG_CACHE_MARKER
    "${SM_FFMPEG_CACHE_INSTALL_DIR}/.itgmania-ffmpeg-${SM_FFMPEG_CACHE_KEY}.complete"
)

set(SM_FFMPEG_REQUIRED_ARTIFACTS
    "${SM_FFMPEG_LIB}/libavformat.a"
    "${SM_FFMPEG_LIB}/libavcodec.a"
    "${SM_FFMPEG_LIB}/libswscale.a"
    "${SM_FFMPEG_LIB}/libavutil.a"
    "${SM_FFMPEG_INCLUDE}/libavformat/avformat.h"
    "${SM_FFMPEG_CACHE_MARKER}")

set(SM_FFMPEG_CACHE_COMPLETE TRUE)
foreach(artifact IN LISTS SM_FFMPEG_REQUIRED_ARTIFACTS)
  if(NOT EXISTS "${artifact}")
    set(SM_FFMPEG_CACHE_COMPLETE FALSE)
    break()
  endif()
endforeach()
