on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

name: Continuous integration

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel, windows-2022]
        include:
          - os: ubuntu-24.04
            name: Ubuntu (x86_64)
            system-deps: sudo apt-get update && sudo apt-get install -y libasound2-dev libgtk-3-dev libjack-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev libxrandr-dev libxtst-dev nasm autoconf autoconf-archive automake libtool pkg-config
          - os: ubuntu-24.04-arm
            name: Ubuntu (ARM)
            system-deps: sudo apt-get update && sudo apt-get install -y libasound2-dev libgtk-3-dev libjack-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev libxrandr-dev libxtst-dev nasm autoconf autoconf-archive automake libtool pkg-config
          # on mac we need autoconf, automake, libtool, pkg-config for libusb
          - os: macos-15
            name: macOS (M1)
            system-deps: brew install nasm autoconf autoconf-archive automake libtool pkg-config
          - os: macos-15-intel
            name: macOS (Intel)
            system-deps: brew install nasm autoconf autoconf-archive automake libtool pkg-config
          - os: windows-2022
            name: Windows
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        if: matrix.os != 'windows-2022'
        run: ${{ matrix.system-deps }}

      - name: Setup vcpkg
        shell: bash
        run: |
          if [ ! -d "$HOME/vcpkg" ]; then
            git clone https://github.com/microsoft/vcpkg.git $HOME/vcpkg
            cd $HOME/vcpkg
            ./bootstrap-vcpkg.sh
          fi
          echo "VCPKG_ROOT=$HOME/vcpkg" >> $GITHUB_ENV

      - name: Add msbuild to PATH
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Configure
        shell: bash
        run: |
          JOBS=$([ "$(uname)" == "Darwin" ] && sysctl -n hw.logicalcpu || nproc)
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmake -B build \
              -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_TARGET_TRIPLET=x64-windows-static \
              -DWITH_FFMPEG_JOBS="%NUMBER_OF_PROCESSORS%"
          else
            cmake -B build \
              -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
              -DWITH_FFMPEG_JOBS=$JOBS
          fi

      - name: Build
        shell: bash
        run: |
          JOBS=$([ "$(uname)" == "Darwin" ] && sysctl -n hw.logicalcpu || nproc || echo 1)
          cmake --build build --parallel $JOBS

  validate-xml-docs:
    name: Validate Lua.xml, LuaDocumentation.xml
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - name: Validate Lua.xml
        run: xmllint --noout Docs/Luadoc/Lua.xml
      - name: Validate LuaDocumentation.xml
        run: xmllint --noout Docs/Luadoc/LuaDocumentation.xml
