on:
  push:
    branches:
      - beta
      - release

name: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel, windows-2022]
        club_fantastic: [Off, On]
        include:
          - os: ubuntu-24.04
            name: Ubuntu (x86_64)
            install: sudo apt-get update && sudo apt-get install -y libasound2-dev libgl-dev libglu1-mesa-dev libgtk-3-dev libjack-dev libmad0-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev libxrandr-dev libxtst-dev nasm
            flags: -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM="$(command -v make)" -DCMAKE_C_COMPILER="$(command -v cc)" -DCMAKE_CXX_COMPILER="$(command -v c++)" -DSM_USE_VCPKG=ON -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DWITH_FFMPEG_JOBS="$(nproc)"
            path: build/ITGmania-*.tar.gz
          - os: ubuntu-24.04-arm
            name: Ubuntu (ARM)
            install: sudo apt-get update && sudo apt-get install -y libasound2-dev libgl-dev libglu1-mesa-dev libgtk-3-dev libjack-dev libmad0-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev libxrandr-dev libxtst-dev nasm
            flags: -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM="$(command -v make)" -DCMAKE_C_COMPILER="$(command -v cc)" -DCMAKE_CXX_COMPILER="$(command -v c++)" -DSM_USE_VCPKG=ON -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DWITH_FFMPEG_JOBS="$(nproc)"
            path: build/ITGmania-*.tar.gz
          - os: macos-15
            name: macOS (M1)
            install: brew install nasm autoconf automake libtool
            flags: -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM="$(command -v make)" -DCMAKE_C_COMPILER="$(command -v cc)" -DCMAKE_CXX_COMPILER="$(command -v c++)" -DSM_USE_VCPKG=ON -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DWITH_FFMPEG_JOBS="$(sysctl -n hw.logicalcpu)"
            path: build/ITGmania-*.dmg
          - os: macos-15-intel
            name: macOS (Intel)
            install: brew install nasm autoconf automake libtool
            flags: -G "Unix Makefiles" -DCMAKE_MAKE_PROGRAM="$(command -v make)" -DCMAKE_C_COMPILER="$(command -v cc)" -DCMAKE_CXX_COMPILER="$(command -v c++)" -DSM_USE_VCPKG=ON -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DWITH_FFMPEG_JOBS="$(sysctl -n hw.logicalcpu)"
            path: build/ITGmania-*.dmg
          - os: windows-2022
            name: Windows
            flags: -DSM_USE_VCPKG=ON -DCMAKE_TOOLCHAIN_FILE="${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DWITH_FFMPEG_JOBS="$env:NUMBER_OF_PROCESSORS"
            path: build/ITGmania-*.exe

    name: "${{ matrix.name }} - ClubFantastic: ${{ matrix.club_fantastic }}"

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        if: matrix.os != 'windows-2022'
        run: ${{ matrix.install }}

      - name: Setup vcpkg (non-Windows)
        if: matrix.os != 'windows-2022'
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Setup vcpkg (Windows)
        if: matrix.os == 'windows-2022'
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV

      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2022'
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Create nightly release
        if: github.ref_name == 'beta'
        run: >
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 
          -DWITH_FULL_RELEASE=Off -DWITH_NIGHTLY_RELEASE=On 
          -DWITH_CLUB_FANTASTIC=${{ matrix.club_fantastic }}
          ${{ matrix.flags }}

      - name: Create full release
        if: github.ref_name == 'release'
        run: >
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release 
          -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off 
          -DWITH_CLUB_FANTASTIC=${{ matrix.club_fantastic }}
          ${{ matrix.flags }}

      - name: Create package
        run: |
          if [ "${{ matrix.os }}" = "windows-2022" ]; then
            cmake --build build --config Release --target package
          else
            cmake --build build --target package
          fi
        shell: bash

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: ITGmania-${{ github.sha }}-${{ matrix.os }}-ClubFantastic-${{ matrix.club_fantastic }}
          path: ${{ matrix.path }}
          archive: false

      - uses: actions/attest@v4
        with:
          subject-name: ITGmania-${{ github.sha }}-${{ matrix.os }}-ClubFantastic-${{ matrix.club_fantastic }}
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
