on:
  push:
    branches:
      - beta
      - anananannaan

name: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        include:
          - os: windows-2022
            name: Windows
            configure: cmake -B build -DWITH_FFMPEG_JOBS="$env:NUMBER_OF_PROCESSORS"
            release-nightly: cmake -B build -DWITH_FULL_RELEASE=Off -DWITH_NIGHTLY_RELEASE=On -DWITH_CLUB_FANTASTIC=Off
            release-full: cmake -B build -DWITH_FULL_RELEASE=On -DWITH_NIGHTLY_RELEASE=Off -DWITH_CLUB_FANTASTIC=Off
            package: cmake --build build --config Release --target package
            path: build/ITGmania-*.exe
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install dependencies
        if: matrix.os != 'windows-2022'
        run: ${{ matrix.install }}
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2022'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Create nightly release
        if: github.ref_name == 'beta'
        run: ${{ matrix.release-nightly }}
      - name: Create full release
        if: github.ref_name == 'release'
        run: ${{ matrix.release-full }}
      - name: Create package
        id: package
        run: |
          ${{ matrix.package }}
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: ITGmania-${{ github.sha }}-${{ matrix.name }}
          path: ${{ matrix.path }}
          archive: false
      - uses: actions/attest@v4
        with:
          subject-name: ITGmania-${{ github.sha }}-${{ matrix.name }}
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
